//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PocketXpdfMFCppc.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TEXTONLYDIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_PocketXpdfMFCTYPE           129
#define IDR_CANCEL                      129
#define IDD_CONFIG                      136
#define IDD_GOTO                        137
#define IDR_MENU1                       139
#define IDR_TOOLS                       139
#define IDR_POPUP                       140
#define IDD_WAITDIALOG                  141
#define IDI_FILE                        142
#define IDR_TEXTONLYMENU                143
#define IDR_TEXTONLYCONTEXT             144
#define IDD_PASSWORD                    145
#define IDR_TOOLBAR_VGA                 148
#define IDD_FINDTEXT                    150
#define IDD_IMAGE_PROPS                 151
#define IDD_ABOUTBOX_WIDE               200
#define IDC_STATIC_1                    201
#define IDD_OUTLINE                     201
#define IDC_STATIC_2                    202
#define IDD_MISCPAGE                    202
#define IDC_STATIC_3                    203
#define IDD_BUTTONMAPPINGPAGE           203
#define IDC_STATIC_4                    204
#define IDC_STATIC_5                    205
#define IDC_STATIC_6                    206
#define IDC_STATIC_7                    207
#define IDC_STATIC_8                    208
#define IDS_FILE                        301
#define IDS_TOOLS                       302
#define IDM_NEW                         401
#define IDM_MENU                        402
#define IDC_ANTIALIASING                1000
#define IDC_SPIN1                       1003
#define IDC_LIST1                       1004
#define IDC_MAPFUNCTION                 1006
#define IDC_MAPHWBUTTONS                1007
#define IDC_COMBO3                      1008
#define IDC_MAPBUTTONS                  1008
#define IDC_FILEASSOC                   1010
#define IDC_EDIT1                       1011
#define IDC_HIDESCROLLBARS              1013
#define IDC_CASE                        1013
#define IDC_OWNERPW                     1014
#define IDC_OWNERPW2                    1015
#define IDC_USERPW                      1015
#define IDC_WAITMESSAGE                 1015
#define IDC_TEXT                        1017
#define IDC_FORWARD                     1019
#define IDC_BEGIN                       1023
#define IDC_CHECK1                      1024
#define IDC_MARK_ALL                    1024
#define IDC_IMAGE_SIZE                  1025
#define IDC_RENDER_DPI                  1026
#define IDC_OUTLINE                     1027
#define IDC_SELECTBUTTON                1030
#define ID_MENU_OPEN                    32771
#define ID_MENU_QUIT                    32772
#define ID_NEXT_PAGE                    32773
#define ID_ZOOM_IN                      32774
#define ID_ZOOM_OUT                     32775
#define ID_PREV_PAGE                    32776
#define ID_TOOLS_PREVIOUSPAGE           32778
#define ID_TOOLS_ZOOMUB                 32779
#define ID_TOOLS_ZOOMOUT                32780
#define ID_FILE_OPTIONS                 32781
#define ID_TOOLS_FITSCREENWIDTH         32782
#define ID_TOOLS_FITSCREENHEIGHT        32783
#define ID_TOOLS_GOTOPAGE               32784
#define ID_TOOLS_ROTATE                 32785
#define ID_ROTATE_90                    32786
#define ID_ROTATE_91                    32787
#define ID_ROTATE_180                   32788
#define ID_TOOLS_FULLSCREEN             32789
#define ID_ROTATION_0                   32790
#define ID_TOOLS_VIEWTEXTONLY           32791
#define ID_TOOLS_FONTSIZE               32792
#define ID_FONTSIZE_7                   32793
#define ID_FONTSIZE_8                   32794
#define ID_FONTSIZE_9                   32795
#define ID_FONTSIZE_10                  32796
#define ID_FONTSIZE_11                  32797
#define ID_FONTSIZE_12                  32798
#define ID_FONTSIZE_DOUBLESIZE          32799
#define ID_POPUP_COPY                   32800
#define ID_DRAG_ZOOM                    32801
#define ID_TOOLS_DRAGZOOM               32802
#define ID_POPUP_DRAGZOOM               32803
#define ID_NEXT_SCREEN                  32805
#define ID_PRIOR_SCREEN                 32808
#define ID_TOOLS_NEXTSCREEN             32809
#define ID_TOOLS_PRIORSCREEN            32810
#define ID_TOOLS_NAVIGATION             32811
#define ID_TOOLS_FIND                   32812
#define ID_TOOLS_FIND_NEXT              32813
#define ID_TOOLS_FIND_PRIOR             32816
#define ID_TOOLS_FIND_CLEARMARKS        32818
#define ID_TOOLS_COLUMNBROWSE           32819
#define ID_COLUMNBROWSE_1COLUMN         32820
#define ID_COLUMNBROWSE_2COLUMN         32821
#define ID_COLUMNBROWSE_4COLUMN         32822
#define ID_TOOLS_IMAGE_INFO             32824
#define ID_TOOLS_OUTLINE                32825
#define ID_VIEW_ZOOM                    32830
#define ID_DOC_BOOKMARKS                32831
#define ID_BOOKMARKS_SAVE               32832
#define ID_BOOKMARKS_LOAD               32833
#define ID_BOOKMARK_SAVE_1              32834
#define ID_BOOKMARK_SAVE_2              32835
#define ID_BOOKMARK_SAVE_3              32836
#define ID_BOOKMARK_SAVE_4              32837
#define ID_BOOKMARK_SAVE_5              32838
#define ID_BOOKMARK_LOAD_1              32839
#define ID_BOOKMARK_LOAD_2              32840
#define ID_BOOKMARK_LOAD_3              32841
#define ID_BOOKMARK_LOAD_4              32842
#define ID_BOOKMARK_LOAD_5              32843
#define ID_DOC_RECENTFILES              32844
#define ID_RECENTFILES_1                32845
#define ID_RECENTFILES_2                32846
#define ID_RECENTFILES_3                32847
#define ID_RECENTFILES_4                32848
#define ID_RECENTFILES_5                32849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32850
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
