double fabs(double x);
double floor(double x);
double ceil(double x);
double sqrt(double x);
double pow(double x, double y);
double acos(double x);
double cos(double x);
double asin(double x);
double sin(double x);
double tan(double x);
double atan(double x);
double atan2(double y, double x);
double log(double x);
double log10(double x);
int abs(int a);
char *dtoa(double x, char *result);
